<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.2.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>8a0059ab-65d0-4275-9a8c-6c02896b47e7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatWithTelescope\ChatWithTelescope.csproj" />
    <ProjectReference Include="..\src\Telescope.Aspire.Hosting\Telescope.Aspire.Hosting.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
